### ISSUE TITLE
Question with regards to .trm output files

### ISSUE THREAD

**Issue by adolliou** [rice-solar-physics/HYDRAD#100]
Dear all,

First of all, I thank you for this open source and well documented code.

I have a question with regards to the .trm output files. I appologize if missed some details in the documentation.

According to the documentation, there should be 10 terms in the electron & particle energy conservation lines. I counted 11 in my case (see below an example). Do you know what is the last term ?

As an example, I printed below the lines from the .trm file of the 17th output (at 170 s) from a run starting with the default HYDRAD loop configuration. The "\\\\" indicate a line jump.

1.93750000e+008 \\\\ (s)
-1.43124246e-015	-1.43124246e-015 \\\\ (mass. cons.)
-1.49908643e-009	7.33471709e-012	1.45072043e-007	-1.46578467e-007	3.17119706e-015	0.00000000e+000 \\ (Mom. cons.)
1.35189197e+001	-4.56210929e-003	2.42889049e-007	0.00000000e+000	1.02871666e+001	6.27481861e-004 3.23531618e+000	3.71297473e-004	0.00000000e+000	0.00000000e+000	0.00000000e+000 \\\\ (Electron energy conservation)
-1.02913902e+001	-4.57316149e-003	-4.13154845e-009	7.20854380e-004	-1.02871666e+001	1.00000000e-300	0.00000000e+000	-3.71297473e-004	5.00959779e-012	0.00000000e+000	0.00000000e+000 \\\\ (particle energy conservation)

With regards,

**Comment by sjbradshaw** [comment]
Hi Antoine,

 

Thanks very much for your email – it’s good to know that HYDRAD is being used within the solar community! Thanks also for your questions, which have helped me to identify a small typo in one of the header files. Here are the answers:

 

1.	You are correct. There should only be 10 columns (terms) of output for the energy equations in the .trm files, but HYDRAD is outputting 11. The reason for this is a typo in the header file “HYDRAD/source/cell.h”. Line 29 in this file reads “#define ENERGY_TERMS 10”. If you change it to “#define ENERGY_TERMS 9” then HYDRAD will output the correct number of energy terms, omitting the spurious extra one. I will make a note to update this in the GitHub repository as well.

 

2.	Again, you are correct. Only the electrons are being heated in this example. The ion heating is set to some negligible (essentially, zero) value. This is intentional. In steady-state, some of the energy given to the electrons is then passed onto the ions via Coulomb collisions, so the ion temperature is maintained at (or very close to) the electron temperature. If the ions were heated at the same rate (e.g. H_ion = 6.27e-4 erg cm^-3 s^-1) then they would quickly become much hotter (because the ion thermal conduction is about an order of magnitude weaker than for electrons) and collisionally decouple from the electrons (the collision frequency strongly decreases with increasing temperature). HYDRAD allows for heating electrons and ions separately, or just heating one species, to investigate what might happen. Only heating electrons is roughly equivalent to heating in a single fluid model, because electrons are primarily responsible for distributing the energy (mostly via thermal conduction); however, there is no evidence to prove that only electrons (or, even, primarily electrons) are directly heated in the solar atmosphere. So, HYDRAD accounts for this possibility by, at least, allowing protons to be heated separately.

 

Background heating is always applied to electrons to maintain the steady-state (though it can be switched off); dynamic/time-dependent heating, when selected and defined, can be applied to electrons and ions in different proportions by using the slider (heating options are under the “Physics/Heating” tabs in the GUI).

 

I hope you have found this information helpful. Please get in touch if you have other questions and/or encounter new issues.

 

Best wishes,

 

Steve 

 

 

Dr. Stephen J. Bradshaw

(Professor of Physics and Astronomy / Associate Department Chair)

 

Department of Physics and Astronomy (MS 108)

Rice University,

6100 Main Street,

Houston,

TX 77005,

USA.

 

Tel: +1 713 348 4045

Email: ***@***.*** ***@***.***> 

Web: https://solar.rice.edu <https://solar.rice.edu/> 

GitHub: https://github.com/rice-solar-physics

 

From: Antoine Dolliou ***@***.***> 
Sent: Monday, September 25, 2023 8:40 AM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Question with regards to .trm output files (Issue #100)

 

Dear all,

First of all, I thank you for this open source and well documented code.

I have a few questions with regards to the .trm output files. I appologize if missed some details in the documentation.

1.	According to the documentation, there should be 10 terms in the electron & particle energy conservation lines. I counted 11 in my case (see below an example). Do you know what is the last term ?
2.	The constant background heating term H (6th term, indicated in bold below), is equal to the expected value in the electron energy conservation line, but is equal to 1.00000000e-300 (=0) in the particle energy conservation line. I suppose they should be equal ? Do you know why they are not ?

As an example, I printed below the lines from the .trm file of the 17th iteration from a run starting with the default HYDRAD loop configuration. The "\\" indicate a line jump.

1.93750000e+008 \\ (s)
-1.43124246e-015 -1.43124246e-015 \\ (mass. cons.)
-1.49908643e-009 7.33471709e-012 1.45072043e-007 -1.46578467e-007 3.17119706e-015 0.00000000e+000 \ (Mom. cons.)
1.35189197e+001 -4.56210929e-003 2.42889049e-007 0.00000000e+000 1.02871666e+001 6.27481861e-004 3.23531618e+000 3.71297473e-004 0.00000000e+000 0.00000000e+000 0.00000000e+000 \\ (Electron energy conservation)
-1.02913902e+001 -4.57316149e-003 -4.13154845e-009 7.20854380e-004 -1.02871666e+001 1.00000000e-300 0.00000000e+000 -3.71297473e-004 5.00959779e-012 0.00000000e+000 0.00000000e+000 \\ (particle energy conservation

With regards,

**Comment by adolliou** [comment]
Dear Steve,

Thank you very much for your answer. It was very clear,

Best regards,

Antoine
