### ISSUE TITLE
Using beam heating parameters with no other events

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/HYDRAD#102]
I'm trying to run a beam heating simulation with no other events (i.e. no impulsive events). My `beam_heating_model.cfg` looks like the following

```cfg
1
Time	Energy_flux	Cut-off	Spectral_index
[s]	[erg/cm^2/s]	[keV]
10.0 200000000.0 15.0 7
```

and my `heating_model.cfg` looks like the following,

```cfg
4.50000000e+09 1.00000000e+300 6.026180647986545e-06

0
```

This causes no heating to be configured because of this conditional: https://github.com/rice-solar-physics/HYDRAD/blob/87fe71193be3f66a6797f11eb028bc84f0525f79/Heating_Model/source/heat.cpp#L106-L111

Since the number of events is 0, it returns from this function before configuring the beam. I could of course solve this problem by just adding a "dummy" heating event so that the beam is configured, but I'm curious as to why this conditional exists. Is there some reason that I need to have a typical event configured when I'm using electron beam heating? My understanding was that these two processes can be used independently.

**Comment by sjbradshaw** [comment]
There is no good reason for this. Must be a bug that crept in while “fixing” something else. A beam ought to be runnable whether or not there is any other heating going on. Feel free to fix it.

 

 

 

 

From: Will Barnes ***@***.***> 
Sent: Friday, November 3, 2023 5:54 PM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Using beam heating parameters with no other events (Issue #102)

 

I'm trying to run a beam heating simulation with no other events (i.e. no impulsive events). My beam_heating_model.cfg looks like the following

1
Time    Energy_flux    Cut-off Spectral_index
[s]     [erg/cm^2/s]   [keV]
10.0 200000000.0 15.0 7

and my heating_model.cfg looks like the following,

4.50000000e+09 1.00000000e+300 6.026180647986545e-06
 
0

This causes no heating to be configured because of this conditional: https://github.com/rice-solar-physics/HYDRAD/blob/87fe71193be3f66a6797f11eb028bc84f0525f79/Heating_Model/source/heat.cpp#L106-L111 <https://urldefense.com/v3/__https:/github.com/rice-solar-physics/HYDRAD/blob/87fe71193be3f66a6797f11eb028bc84f0525f79/Heating_Model/source/heat.cpp*L106-L111__;Iw!!BuQPrrmRaQ!kvjgb-zPyXPaKYjEb0uB94JZspdPBfZCPOCE6Ia32JH9mI0DCi7bb7jZrNwb6Om-rmZspu8oTwPas9yXVenV6nddJsX4zsN-dYw$> 

Since the number of events is 0, it returns from this function before configuring the beam. I could of course solve this problem by just adding a "dummy" heating event so that the beam is configured, but I'm curious as to why this conditional exists. Is there some reason that I need to have a typical event configured when I'm using electron beam heating? My understanding was that these two processes can be used independently.

**Comment by wtbarnes** [comment]
Looks like I have to take back what I said previously, even without adding any events, the beam heating parameters are still read in and the beam heating is applied to the simulation. Given that code block above, I don't understand how that's possible though...maybe they are read in and initialized somewhere else?

**Comment by sjbradshaw** [comment]
I should have remembered earlier that beam heating only works when both OPTICALLY_THICK_RADIATION and

NLTE_CHROMOSPHERE are defined. There’s not much point beam heating an isothermal chromosphere; the interaction between the beam electrons and the chromosphere, at a given height in the chromosphere, won’t reproduce any observables because they depend heavily on the structure of the atmosphere.

**Comment by jwreep** [comment]
I'm confused.  The code block linked in heat.cpp does not affect the beam heating, which is read in in a separate function (the next one down).  

Has something changed regarding the chromosphere?

**Comment by wtbarnes** [comment]
> I'm confused. The code block linked in heat.cpp does not affect the beam heating, which is read in in a separate function (the next one down).

You're right. My initial explanation of the issue was wrong. My beam heating configuration was messed up in another place and I was confusing that issue with thinking the beam heating parameters were not being read in.

**Comment by wtbarnes** [comment]
> I should have remembered earlier that beam heating only works when both OPTICALLY_THICK_RADIATION and NLTE_CHROMOSPHERE are defined. There’s not much point beam heating an isothermal chromosphere; the interaction between the beam electrons and the chromosphere, at a given height in the chromosphere, won’t reproduce any observables because they depend heavily on the structure of the atmosphere. 

Ah interesting. This is not something I fully appreciated since I've not thought much about observables in the lower atmosphere in the past.

Interestingly, even *without* the `OPTICALLY_THICK_RADIATION` and `NLTE_CHROMOSPHERE` flags, I do find that an electron beam of moderate strength ($F\approx10^9$ erg $\mathrm{cm}^{-2}\mathrm{s}^{-1}$, $E_C=15$ keV, $\delta=7$, duration of 10 s) leads to fairly significant blue shifts at around 0.5 MK in the first 20 s or so of the simulation. This is in comparison to having an event localized at the loop apex with approximately the same amount of energy (no beam) which produces only red shifts at these same temperatures.  Of course at 0.5 MK, I'm well above the chromosphere.

**Comment by sjbradshaw** [comment]
Did you do something to the code to get it to run without those flags, but with BEAM_HEATING defined? Without those flags it just seg. faults…

**Comment by jwreep** [comment]
I've certainly run beam heating without NLTE_CHROMOSPHERE defined.  I don't recall having any requirement to have that switch turned on for BEAM_HEATING unless a more recent update changed something?  I can't remember whether I have done so without OPTICALLY_THICK_RADIATION, but that might overlap with the column density calculation.  

Could you upload the configuration you're running, Will?

**Comment by sjbradshaw** [comment]
If I just create the default initial conditions, choose beam heating, and then run HYDRAD then I get a seg. fault. For me, choosing OPTICALLY_THICK_RADIATION and NLTE_CHROMOSPHERE resolves it. I haven’t looked into it for the reasons I described earlier (the isothermal, stratified chromosphere’s interaction with the beam isn’t very physical). However, I guess it could be a useful option for test / exploratory calculations.

**Comment by wtbarnes** [comment]
The only thing I did was add a `#define BEAM_HEATING` to `Radiation_Model/source/config.h`. I'm not sure if the GUI was doing this already, but the Python tools were missing this and without it, I was getting a compilation error (not a runtime error).

I've attached a run here (without any of the results or compiled executables) that includes the entire configuration that compiles and runs on my machine.

[beam_heating_example.tar.gz](https://github.com/rice-solar-physics/HYDRAD/files/13340154/beam_heating_example.tar.gz)

**Comment by wtbarnes** [comment]
> If I just create the default initial conditions, choose beam heating, and then run HYDRAD then I get a seg. fault. For me, choosing OPTICALLY_THICK_RADIATION and NLTE_CHROMOSPHERE resolves it.

Interesting. I'm using `pydrad` to configure the run instead of the GUI. In `pydrad`, I've tried to mimic the logic of how the GUI sets the preprocessor directives and writes the configuration files, but it seems there are cases where the behavior differs.

**Comment by sjbradshaw** [comment]
Well, if it somehow works via pydrad then I wouldn’t question it…

**Comment by jwreep** [comment]
> The only thing I did was add a #define BEAM_HEATING to Radiation_Model/source/config.h. 

It needs to be defined in `Heating_Model/source/config.h` as well.

**Comment by sjbradshaw** [comment]
Defining BEAM_HEATING in Radiation_Model/source/config.h seems to have fixed it for me. Cheers!

 

I’ll make an update for the public version on GitHub.

**Comment by wtbarnes** [comment]
Yeah I had it defined there, but it does not get picked up in `Radiation_Model/source/config.h` so it needs to be defined both places.

**Comment by wtbarnes** [comment]
> Defining BEAM_HEATING in Radiation_Model/source/config.h seems to have fixed it for me. Cheers! I’ll make an update for the public version on GitHub. 

Great! I'm still confused as to how this leads to a seg fault and not a compile time error (because `BEAM_HEATING` is not defined), but maybe that's down to different compilers and operating systems?

**Comment by wtbarnes** [comment]
Great! I'll go ahead and close this since its been fixed in the GUI and on the `pydrad` side.
