### ISSUE TITLE
Seg fault on Initial Conditions 

### ISSUE THREAD

**Issue by junverferth** [rice-solar-physics/HYDRAD#95]
Error using mingw64 and g++ on windows 10.

on a fresh download of hydrad and a fresh download of mingw (x86_64-8.1.0-release-posix-seh-rt_v6-rev0) to provide gcc and g++ on windows (other versions of mingw also cause the same problem)

mingw placed onto the system path

initial conditions compile and run. Using the default settings from the GUI to run a test simulation.

Outputs initial.amr.gravity and initial.amr.table and encounters a segfault in writing the .amr file.

testing/fiddling finds that the segfault is inside writeAMRfile, in either of the two ppiID loops at lines 156 and 167.

Adjusting the minimum cells, the error occurs at just past 50% of the array allocation. 

If one reduces the minimum grid cells and refinement to absurdly low values (4-6 grid cells and refinement 0 or 1) then the .amr file writes but still crashes in writing the subsequent files.

No issues encountered if a uniform grid is requested, even up to 10k cells.

uploading the same files to a linux machine and running through commandline works, so the problem lies with the windows side of the problem.

running Initial_Conditions.bat in the main dir gives the following output.

C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022\Initial_Conditions\build_scripts>g++ -O3 -flto -Wall -Wno-unused-variable -Wno-write-strings ../source/main.cpp ../source/ode.cpp ../source/misc.cpp ../../Radiation_Model/source/element.cpp ../../Radiation_Model/source/radiation.cpp ../../Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp ../../Radiation_Model/source/OpticallyThick/RadiativeRates.cpp ../../Resources/source/gammabeta.cpp ../../Resources/source/fitpoly.cpp ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp ../../Resources/Utils/regPoly/regpoly.cpp ../../Resources/Utils/regPoly/nrutil.cpp ../../Resources/source/file.cpp -o ../../Initial_Conditions.exe
  In member function 'OpenPieceWiseFit',
      inlined from '__ct_base ' at ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:32:18,
      inlined from 'main' at ../source/main.cpp:93:73:
  ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:59:38: warning: argument 1 range [18446744056529682432, 18446744073709551608] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     ppfSDCoefficient = (double**)malloc( sizeof(double*) * inumSD );
                                        ^
  ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp: In function 'main':
  C:/Users/junverferth/MHD/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/stdlib.h:503:17: note: in a call to allocation function 'malloc' declared here
     void *__cdecl malloc(size_t _Size);
                   ^
  In member function 'OpenPieceWiseFit',
      inlined from '__ct_base ' at ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:32:18,
      inlined from 'main' at ../source/main.cpp:93:73:
  ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:60:33: warning: argument 1 range [18446744056529682432, 18446744073709551608] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     ppfSDMinMax = (double**)malloc( sizeof(double*) * inumSD );
                                   ^
  ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp: In function 'main':
  C:/Users/junverferth/MHD/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/stdlib.h:503:17: note: in a call to allocation function 'malloc' declared here
     void *__cdecl malloc(size_t _Size);
                   ^
  
  C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022\Initial_Conditions\build_scripts>cd ../..
  
  C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022>Initial_Conditions.exe
  
  
  Calculating initial hydrostatic conditions...
  
  Peak heating range = 6.2661e-004 -> 6.2806e-004 erg cm^-3 s^-1
  
  Optimum peak heating rate = 6.2748e-004 erg cm^-3 s^-1
  
  Writing initial conditions file...
  
  
  C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022>

**Comment by sjbradshaw** [comment]
Hmmm… Thanks for the feedback, very interesting. I’ve not used mingw64 for g++ under Windows before, preferring cygwin instead – which has not given me any problems like this. Evidently, the Windows 10 version of mingw64 is doing something odd / different with memory allocation.

 

I spotted one possible issue on Line 154 of Initial_Conditions/source/misc.cpp. Try replacing that line with the following:

 

Line 154: ppiID = (long**)malloc( sizeof(long*) * iMAX_CELLS );

 

Since it is allocating memory for an array of pointers to pointers then the byte length of a pointer to the variable type (long int) should be passed to the sizeof() function, rather than the byte length of the variable type itself. I’m not confident it will work, but it’s a first thing to try. Otherwise, a “fix” to at least get up and running under Win 10 is to use cygwin to provide Linux-like functionality.

 

Cheers,

 

Steve

 

 

From: junverferth ***@***.***> 
Sent: Wednesday, October 12, 2022 7:00 AM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Seg fault on Initial Conditions (Issue #95)

 

Error using mingw64 and g++ on windows 10.

on a fresh download of hydrad and a fresh download of mingw (x86_64-8.1.0-release-posix-seh-rt_v6-rev0) to provide gcc and g++ on windows (other versions of mingw also cause the same problem)

mingw placed onto the system path

initial conditions compile and run. Using the default settings from the GUI to run a test simulation.

Outputs initial.amr.gravity and initial.amr.table and encounters a segfault in writing the .amr file.

testing/fiddling finds that the segfault is inside writeAMRfile, in either of the two ppiID loops at lines 156 and 167.

Adjusting the minimum cells, the error occurs at just past 50% of the array allocation.

If one reduces the minimum grid cells and refinement to absurdly low values (4-6 grid cells and refinement 0 or 1) then the .amr file writes but still crashes in writing the subsequent files.

No issues encountered if a uniform grid is requested, even up to 10k cells.

uploading the same files to a linux machine and running through commandline works, so the problem lies with the windows side of the problem.

running Initial_Conditions.bat in the main dir gives the following output.

C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022\Initial_Conditions\build_scripts>g++ -O3 -flto -Wall -Wno-unused-variable -Wno-write-strings ../source/main.cpp ../source/ode.cpp ../source/misc.cpp ../../Radiation_Model/source/element.cpp ../../Radiation_Model/source/radiation.cpp ../../Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp ../../Radiation_Model/source/OpticallyThick/RadiativeRates.cpp ../../Resources/source/gammabeta.cpp ../../Resources/source/fitpoly.cpp ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp ../../Resources/Utils/regPoly/regpoly.cpp ../../Resources/Utils/regPoly/nrutil.cpp ../../Resources/source/file.cpp -o ../../Initial_Conditions.exe
In member function 'OpenPieceWiseFit',
inlined from '__ct_base ' at ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:32:18,
inlined from 'main' at ../source/main.cpp:93:73:
../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:59:38: warning: argument 1 range [18446744056529682432, 18446744073709551608] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
ppfSDCoefficient = (double**)malloc( sizeof(double*) * inumSD );
^
../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp: In function 'main':
C:/Users/junverferth/MHD/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/stdlib.h:503:17: note: in a call to allocation function 'malloc' declared here
void __cdecl malloc(size_t _Size);
^
In member function 'OpenPieceWiseFit',
inlined from '__ct_base ' at ../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:32:18,
inlined from 'main' at ../source/main.cpp:93:73:
../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp:60:33: warning: argument 1 range [18446744056529682432, 18446744073709551608] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
ppfSDMinMax = (double*)malloc( sizeof(double*) * inumSD );
^
../../Resources/Utils/generatePieceWiseFit/source/piecewisefit.cpp: In function 'main':
C:/Users/junverferth/MHD/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/stdlib.h:503:17: note: in a call to allocation function 'malloc' declared here
void *__cdecl malloc(size_t _Size);
^

C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022\Initial_Conditions\build_scripts>cd ../..

C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022>Initial_Conditions.exe

Calculating initial hydrostatic conditions...

Peak heating range = 6.2661e-004 -> 6.2806e-004 erg cm^-3 s^-1

Optimum peak heating rate = 6.2748e-004 erg cm^-3 s^-1

Writing initial conditions file...

C:\Users\junverferth\MHD\HYDRAD\HYDRAD-10-11-2022>

**Comment by junverferth** [comment]
Swapping over to Line 154: ppiID = (long**)malloc( sizeof(long*) * iMAX_CELLS ); 
did fix the issue.
Looking into it in mingw for whatever reason, a long is 4 bytes and the long pointer is 8, instead of both being 8.
